### PR TITLE
asking you to pul the new function.... not the manual change... but not sure how:)

### PR DESCRIPTION
**Pull request by JRLLRJ**

### CODE REVIEW

**Comment by malecki** [comment]
Hm. I don't think I like this. I can see either having an argument or running a check for the form of the data and then matching it to the population cells, but users shouldn't have to see the cell-level polldata. In stanmrp they won't because it won't exist.. I don't even like exposing the `getData` method.

**Comment by JRLLRJ** [comment]
But im going to need it to develop mrp extensions and therefore so might others. We need not highlight it.

It will be needed to do nested mrp for now etc.

**Comment by malecki** [comment]
not sure that's true.

``` R
mrp.yes <- mrp(full mrp call here)
dataForNested <- makeNestedData(getData(mrp.yes))
mrp.no <- mrp.yes
mrp.no@data <- dataForNested
mrp.no <- mr(mrp.no, …)

```

**Comment by JRLLRJ** [comment]
not following all of the below…   3rd line?

You need to modify the population weights for the 2nd stage bc  what was (cell weight) will be (1- fitted(model))*cellweight or whatever.  

even below the data will have to be changed, bc you need to drop some of the data -- all those who said yes… so you need to modify getData(mrp.yes)

no?

**Comment by malecki** [comment]
hm. ok — the solution should be to take a `cellData` argument (default null) and allow `data` to be null. What do you do to prepare one-run cell data for a nested second run? There really should not be a reason to ‘convert back’ to indiv then cell again.
`nestedMrp(mrp, dataTransformation=fun, populationTransformation=fun)`

**Comment by JRLLRJ** [comment]
there shouldn't be… the reason there is is that MRP runs on cell level data and the dumb world runs on individual data. :)

Well…. hmm….  After MRP.yesvsnoDK…. I take original individual data and drop yes people and keep no and DK people.    going to run 1= no and 0  = DK model.

so far so good.  Don't need innards of mrp.yesvsnoDK.

I have the percent in each cell that says yes and can poststatify that normally.

But then I need to have a Census type data frame… which is cell level…. that takes the fitted(mrp.yesvsnoDK) multiplies it by the pop.weights at the cell level…   (1-fitted) \* pop.weight is what I need actually…. so far so good.   THAT becomes new pop.weights variable…   fitted(mrp.novsDK) \*  new popweightsvar…. = the   "no"s?    That is…. the cell level percent no is …. fitted(mrp.novsDK) \* (1-fitted(mrp.YesvsNoDK)) \* (original pop weights)

so maybe you are right?

It's just that the output of mrp is cell level data…. but since the only input to mrp is individual level data it seems weird to not be able to get back to it….  But maybe I can always just modify the ORIGINAL individual level data to do what I want… 

sorry to harp on all this if I turn out to have been wrong :)

**Comment by malecki** [comment]
I pulled this to a branch 'nested' . you can fetch upstream and `git checkout -t upstream/nested`

**Pull request closed without merging**
